[workspace]
members = [
    "lib",
    "examples/verify_account",
    "examples/verify_storage",
    "examples/verify_header",
    "examples/verify_transaction",
    "examples/verify_receipt",
    "zkcross/lib",
    "zkcross/examples/af",
    "zkcross/examples/svf",
    "zkcross/examples/rvf",
    "zkcross/examples/stf",
    "zkcross/examples/zkcross",
    "zkcross/examples/zkcross_compliance",
]
default-member = "lib"
