[account_old]
address = [216, 218, 107, 242, 105, 74, 249, 215, 238, 237, 224, 63, 83, 65, 83, 55, 170, 150, 69, 0]
balance = "0"
code_hash = [197, 94, 119, 16, 236, 157, 250, 168, 243, 68, 212, 135, 41, 90, 232, 107, 245, 238, 221, 15, 224, 84, 22, 156, 67, 225, 114, 66, 215, 119, 88, 164]
nonce = 0
storage_hash = [86, 232, 31, 23, 27, 204, 85, 166, 255, 131, 69, 230, 146, 192, 248, 110, 91, 72, 224, 27, 153, 108, 173, 192, 241, 9, 227, 197, 61, 46, 169, 72]

[proof_old]
key = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 216, 218, 107, 242, 105, 74, 249, 215, 238, 237, 224, 63, 83, 65, 83, 55, 170, 150, 69, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
value = [226, 128, 160, 0, 160, 0, 160, 197, 94, 119, 16, 236, 157, 250, 168, 243, 68, 212, 135, 41, 90, 232, 107, 245, 238, 221, 15, 224, 84, 22, 156, 67, 225, 114, 66, 215, 119, 88, 164, 160, 86, 232, 31, 23, 27, 204, 85, 166, 255, 131, 69, 230, 146, 192, 248, 110, 91, 72, 224, 27, 153, 108, 173, 192, 241, 9, 227, 197, 61, 46, 169, 72, 160, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128]

[[proof_old.proof.nodes]]
[[proof_old.proof.nodes]]
[[proof_old.proof.nodes]]
[[proof_old.proof.nodes]]
[[proof_old.proof.nodes]]
[[proof_old.proof.nodes]]
[[proof_old.proof.nodes]]
[[proof_old.proof.nodes]]

proof_old.proof.leaf = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
proof_old.proof.depth = 0

state_root_old = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[account_new]
address = [216, 218, 107, 242, 105, 74, 249, 215, 238, 237, 224, 63, 83, 65, 83, 55, 170, 150, 69, 0]
balance = "0"
code_hash = [197, 94, 119, 16, 236, 157, 250, 168, 243, 68, 212, 135, 41, 90, 232, 107, 245, 238, 221, 15, 224, 84, 22, 156, 67, 225, 114, 66, 215, 119, 88, 164]
nonce = 0
storage_hash = [86, 232, 31, 23, 27, 204, 85, 166, 255, 131, 69, 230, 146, 192, 248, 110, 91, 72, 224, 27, 153, 108, 173, 192, 241, 9, 227, 197, 61, 46, 169, 72]

[proof_new]
key = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 216, 218, 107, 242, 105, 74, 249, 215, 238, 237, 224, 63, 83, 65, 83, 55, 170, 150, 69, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
value = [226, 128, 160, 0, 160, 0, 160, 197, 94, 119, 16, 236, 157, 250, 168, 243, 68, 212, 135, 41, 90, 232, 107, 245, 238, 221, 15, 224, 84, 22, 156, 67, 225, 114, 66, 215, 119, 88, 164, 160, 86, 232, 31, 23, 27, 204, 85, 166, 255, 131, 69, 230, 146, 192, 248, 110, 91, 72, 224, 27, 153, 108, 173, 192, 241, 9, 227, 197, 61, 46, 169, 72, 160, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128]

[[proof_new.proof.nodes]]
[[proof_new.proof.nodes]]
[[proof_new.proof.nodes]]
[[proof_new.proof.nodes]]
[[proof_new.proof.nodes]]
[[proof_new.proof.nodes]]
[[proof_new.proof.nodes]]
[[proof_new.proof.nodes]]

proof_new.proof.leaf = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
proof_new.proof.depth = 0

state_root_new = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
